package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String numeroIdentificacion;
     private String nombre;
     private String apellidos;
     private String domicilio;
     private String correo;
     private String telefono;
     private String password;
     private Set tarjetas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String numeroIdentificacion, String nombre, String apellidos, String domicilio, String correo, String telefono, String password) {
        this.numeroIdentificacion = numeroIdentificacion;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.domicilio = domicilio;
        this.correo = correo;
        this.telefono = telefono;
        this.password = password;
    }
    public Cliente(String numeroIdentificacion, String nombre, String apellidos, String domicilio, String correo, String telefono, String password, Set tarjetas) {
       this.numeroIdentificacion = numeroIdentificacion;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.domicilio = domicilio;
       this.correo = correo;
       this.telefono = telefono;
       this.password = password;
       this.tarjetas = tarjetas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set tarjetas) {
        this.tarjetas = tarjetas;
    }




}


