package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Tarjeta tarjeta;
     private Viaje viaje;
     private Date fechaPago;
     private float importe;
     private int numeroViajeros;
     private String localizador;
     private Set ocupacions = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Tarjeta tarjeta, Viaje viaje, Date fechaPago, float importe, int numeroViajeros, String localizador) {
        this.tarjeta = tarjeta;
        this.viaje = viaje;
        this.fechaPago = fechaPago;
        this.importe = importe;
        this.numeroViajeros = numeroViajeros;
        this.localizador = localizador;
    }
    public Compra(Tarjeta tarjeta, Viaje viaje, Date fechaPago, float importe, int numeroViajeros, String localizador, Set ocupacions) {
       this.tarjeta = tarjeta;
       this.viaje = viaje;
       this.fechaPago = fechaPago;
       this.importe = importe;
       this.numeroViajeros = numeroViajeros;
       this.localizador = localizador;
       this.ocupacions = ocupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }
    public int getNumeroViajeros() {
        return this.numeroViajeros;
    }
    
    public void setNumeroViajeros(int numeroViajeros) {
        this.numeroViajeros = numeroViajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


