package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private String cif;
     private String nombre;
     private int telefono;
     private String direccion;
     private String logo;
     private int numeroPlazas;

    public Empresa() {
    }

    public Empresa(String cif, String nombre, int telefono, String direccion, String logo, int numeroPlazas) {
       this.cif = cif;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.logo = logo;
       this.numeroPlazas = numeroPlazas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public int getNumeroPlazas() {
        return this.numeroPlazas;
    }
    
    public void setNumeroPlazas(int numeroPlazas) {
        this.numeroPlazas = numeroPlazas;
    }




}


