package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Integer id;
     private String nombreEstacion;
     private String direccion;
     private Set rutasForEstacionDestino = new HashSet(0);
     private Set rutasForEstacionOrigen = new HashSet(0);

    public Estacion() {
    }

	
    public Estacion(String nombreEstacion, String direccion) {
        this.nombreEstacion = nombreEstacion;
        this.direccion = direccion;
    }
    public Estacion(String nombreEstacion, String direccion, Set rutasForEstacionDestino, Set rutasForEstacionOrigen) {
       this.nombreEstacion = nombreEstacion;
       this.direccion = direccion;
       this.rutasForEstacionDestino = rutasForEstacionDestino;
       this.rutasForEstacionOrigen = rutasForEstacionOrigen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreEstacion() {
        return this.nombreEstacion;
    }
    
    public void setNombreEstacion(String nombreEstacion) {
        this.nombreEstacion = nombreEstacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getRutasForEstacionDestino() {
        return this.rutasForEstacionDestino;
    }
    
    public void setRutasForEstacionDestino(Set rutasForEstacionDestino) {
        this.rutasForEstacionDestino = rutasForEstacionDestino;
    }
    public Set getRutasForEstacionOrigen() {
        return this.rutasForEstacionOrigen;
    }
    
    public void setRutasForEstacionOrigen(Set rutasForEstacionOrigen) {
        this.rutasForEstacionOrigen = rutasForEstacionOrigen;
    }




}


