package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer id;
     private Ruta ruta;
     private Date horaSalida;
     private Date horaLlegada;
     private char dia;
     private Set viajes = new HashSet(0);
     private Set viajeBackups = new HashSet(0);

    public Horario() {
    }

	
    public Horario(Ruta ruta, Date horaSalida, Date horaLlegada, char dia) {
        this.ruta = ruta;
        this.horaSalida = horaSalida;
        this.horaLlegada = horaLlegada;
        this.dia = dia;
    }
    public Horario(Ruta ruta, Date horaSalida, Date horaLlegada, char dia, Set viajes, Set viajeBackups) {
       this.ruta = ruta;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.dia = dia;
       this.viajes = viajes;
       this.viajeBackups = viajeBackups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public char getDia() {
        return this.dia;
    }
    
    public void setDia(char dia) {
        this.dia = dia;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }
    public Set getViajeBackups() {
        return this.viajeBackups;
    }
    
    public void setViajeBackups(Set viajeBackups) {
        this.viajeBackups = viajeBackups;
    }




}


