package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1



/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Viajero viajero;
     private int numeroAsiento;
     private float importe;

    public Ocupacion() {
    }

    public Ocupacion(Compra compra, Viajero viajero, int numeroAsiento, float importe) {
       this.compra = compra;
       this.viajero = viajero;
       this.numeroAsiento = numeroAsiento;
       this.importe = importe;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Viajero getViajero() {
        return this.viajero;
    }
    
    public void setViajero(Viajero viajero) {
        this.viajero = viajero;
    }
    public int getNumeroAsiento() {
        return this.numeroAsiento;
    }
    
    public void setNumeroAsiento(int numeroAsiento) {
        this.numeroAsiento = numeroAsiento;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }




}


