package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1



/**
 * OcupacionBackup generated by hbm2java
 */
public class OcupacionBackup  implements java.io.Serializable {


     private int id;
     private CompraBackup compraBackup;
     private ViajeroBackup viajeroBackup;
     private int numeroAsiento;
     private float importe;

    public OcupacionBackup() {
    }
    
    public OcupacionBackup(Ocupacion ocupacion){
        this.id = ocupacion.getId();
        //this.idViajero = ocupacion.getViajero().getId();
        this.numeroAsiento = ocupacion.getNumeroAsiento();
        //this.idCompra = ocupacion.getCompra().getId();
        this.importe = ocupacion.getImporte();
    }

    public OcupacionBackup(int id, CompraBackup compraBackup, ViajeroBackup viajeroBackup, int numeroAsiento, float importe) {
       this.id = id;
       this.compraBackup = compraBackup;
       this.viajeroBackup = viajeroBackup;
       this.numeroAsiento = numeroAsiento;
       this.importe = importe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CompraBackup getCompraBackup() {
        return this.compraBackup;
    }
    
    public void setCompraBackup(CompraBackup compraBackup) {
        this.compraBackup = compraBackup;
    }
    public ViajeroBackup getViajeroBackup() {
        return this.viajeroBackup;
    }
    
    public void setViajeroBackup(ViajeroBackup viajeroBackup) {
        this.viajeroBackup = viajeroBackup;
    }
    public int getNumeroAsiento() {
        return this.numeroAsiento;
    }
    
    public void setNumeroAsiento(int numeroAsiento) {
        this.numeroAsiento = numeroAsiento;
    }
    public float getImporte() {
        return this.importe;
    }
    
    public void setImporte(float importe) {
        this.importe = importe;
    }




}


