package POJO;
// Generated 06-mar-2019 15:50:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer id;
     private Estacion estacionByEstacionDestino;
     private Estacion estacionByEstacionOrigen;
     private float distancia;
     private String tiempoEstimado;
     private float precio;
     private Set horarios = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(Estacion estacionByEstacionDestino, Estacion estacionByEstacionOrigen, float distancia, String tiempoEstimado, float precio) {
        this.estacionByEstacionDestino = estacionByEstacionDestino;
        this.estacionByEstacionOrigen = estacionByEstacionOrigen;
        this.distancia = distancia;
        this.tiempoEstimado = tiempoEstimado;
        this.precio = precio;
    }
    public Ruta(Estacion estacionByEstacionDestino, Estacion estacionByEstacionOrigen, float distancia, String tiempoEstimado, float precio, Set horarios) {
       this.estacionByEstacionDestino = estacionByEstacionDestino;
       this.estacionByEstacionOrigen = estacionByEstacionOrigen;
       this.distancia = distancia;
       this.tiempoEstimado = tiempoEstimado;
       this.precio = precio;
       this.horarios = horarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estacion getEstacionByEstacionDestino() {
        return this.estacionByEstacionDestino;
    }
    
    public void setEstacionByEstacionDestino(Estacion estacionByEstacionDestino) {
        this.estacionByEstacionDestino = estacionByEstacionDestino;
    }
    public Estacion getEstacionByEstacionOrigen() {
        return this.estacionByEstacionOrigen;
    }
    
    public void setEstacionByEstacionOrigen(Estacion estacionByEstacionOrigen) {
        this.estacionByEstacionOrigen = estacionByEstacionOrigen;
    }
    public float getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(float distancia) {
        this.distancia = distancia;
    }
    public String getTiempoEstimado() {
        return this.tiempoEstimado;
    }
    
    public void setTiempoEstimado(String tiempoEstimado) {
        this.tiempoEstimado = tiempoEstimado;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


